replace auction related term to listing
UnUniFi/chain pull request #186
Opened 2022-06-02 13:13 UTC by jununifi

2022-06-05 13:58 UTC, mkXultra requested changes

2022-06-05 13:58 UTC, mkXultra commented on x/nftmarket/spec/01_concepts_en.md
> +1. for synthetic asset creation type listings, BT can use any token supported by UnUniFi (global_option)
@jununifi 
Duplicate?

2022-06-06 09:51 UTC, jununifi commented on x/nftmarket/spec/01_concepts_en.md
> +1. for synthetic asset creation type listings, BT can use any token supported by UnUniFi (global_option)
What you mean by duplicate here?

2022-06-06 10:17 UTC, mkXultra approved these changes

2022-06-06 10:51 UTC, merged