derivatives implment
UnUniFi/chain pull request #307
Opened 2022-12-20 02:29 UTC by inotite

2022-12-21 03:23 UTC, KimuraYu45z requested changes

2022-12-21 03:23 UTC, KimuraYu45z commented on proto/derivatives/derivatives.proto
> +  repeated Asset accepted_asstes = 1 [
typo here

2023-02-20 15:35 UTC, Senna46 commented
It appears that there was a change in one of the last three commits that caused the chain to not start up.
Do you fix it?
`panic: value from ParamSetPair is invalid: oracle 0 is empty`

2023-03-15 08:19 UTC, KimuraYu45z approved these changes

2023-03-15 08:21 UTC, merged