impl fn to detemine initial lpt supply amount
UnUniFi/chain pull request #389
Opened 2023-02-21 04:42 UTC by taiki1frsh

Addressed issues: #364 and #370 
beside, impled very simple test for newly added fn.

2023-02-22 04:43 UTC, mkXultra requested changes

2023-02-22 04:43 UTC, mkXultra commented on x/derivatives/keeper/lpt_test.go
> +	assetMarketCap := assetPrice.Price.Mul(sdk.NewDecFromInt(sdk.OneInt()))
do not use other func.
Please hard code the data.

2023-02-22 04:43 UTC, mkXultra commented on x/derivatives/keeper/lpt.go
> +func (k Keeper) DetermineMintingLPTokenAmount(ctx sdk.Context, amount sdk.Coin) (sdk.Coin, sdk.Coin, error) {
plz make test

2023-02-22 08:00 UTC, mkXultra commented on x/derivatives/keeper/lpt_test.go
> +	suite.Require().Condition(initialLPTSupply.Amount.IsPositive)
check initialLPTSupply value

2023-02-24 05:07 UTC, taiki1frsh commented on x/derivatives/keeper/lpt_test.go
> +	suite.Require().Condition(initialLPTSupply.Amount.IsPositive)
fixed.

2023-02-27 03:48 UTC, mkXultra approved these changes

2023-02-27 04:05 UTC, merged